-- Add LayBack mode fields to apostas table
ALTER TABLE public.apostas 
ADD COLUMN IF NOT EXISTS modo_entrada TEXT NOT NULL DEFAULT 'PADRAO',
ADD COLUMN IF NOT EXISTS lay_exchange TEXT,
ADD COLUMN IF NOT EXISTS lay_odd NUMERIC,
ADD COLUMN IF NOT EXISTS lay_stake NUMERIC,
ADD COLUMN IF NOT EXISTS lay_liability NUMERIC,
ADD COLUMN IF NOT EXISTS lay_comissao NUMERIC DEFAULT 5;