
-- PASSO 1: Primeiro adicionar GIRO_GRATIS à constraint ANTES de converter os registros
ALTER TABLE cash_ledger DROP CONSTRAINT IF EXISTS cash_ledger_tipo_transacao_check;

ALTER TABLE cash_ledger ADD CONSTRAINT cash_ledger_tipo_transacao_check 
CHECK (tipo_transacao IN (
  'DEPOSITO', 'SAQUE', 'TRANSFERENCIA', 'APORTE_FINANCEIRO',
  'APOSTA_GREEN', 'APOSTA_RED', 'APOSTA_VOID', 'APOSTA_REVERSAO',
  'BONUS_CREDITADO', 'BONUS_ESTORNO', 'FREEBET_CREDITADO', 'FREEBET_USADO',
  'CASHBACK_MANUAL', 'CASHBACK_ESTORNO', 'GIRO_GRATIS',
  'AJUSTE_SALDO', 'AJUSTE_MANUAL',
  'PAGTO_PARCEIRO', 'PAGTO_FORNECEDOR', 'PAGTO_OPERADOR',
  'COMISSAO_INDICADOR', 'BONUS_INDICADOR',
  'DESPESA_ADMINISTRATIVA', 'CONCILIACAO',
  'PERDA_CAMBIAL', 'GANHO_CAMBIAL',
  'CREDITO_GIRO'
));
