ALTER TABLE public.cash_ledger DROP CONSTRAINT cash_ledger_tipo_transacao_check;

ALTER TABLE public.cash_ledger ADD CONSTRAINT cash_ledger_tipo_transacao_check CHECK (tipo_transacao = ANY (ARRAY[
  'AJUSTE_SALDO','AJUSTE_MANUAL','AJUSTE_POSITIVO','AJUSTE_NEGATIVO','AJUSTE_RECONCILIACAO',
  'CASHBACK_MANUAL','CASHBACK_ESTORNO',
  'APOSTA_GREEN','APOSTA_RED','APOSTA_VOID','APOSTA_MEIO_GREEN','APOSTA_MEIO_RED','APOSTA_REVERSAO',
  'BONUS_CREDITADO','BONUS_ESTORNO',
  'GIRO_GRATIS','GIRO_GRATIS_ESTORNO',
  'DEPOSITO','SAQUE','TRANSFERENCIA',
  'APORTE_FINANCEIRO','PERDA_OPERACIONAL','PERDA_REVERSAO',
  'CONCILIACAO','ESTORNO','EVENTO_PROMOCIONAL',
  'GANHO_CAMBIAL','PERDA_CAMBIAL',
  'PAGTO_PARCEIRO','PAGTO_FORNECEDOR','PAGTO_OPERADOR',
  'COMISSAO_INDICADOR','BONUS_INDICADOR',
  'DESPESA_ADMINISTRATIVA',
  'APORTE_INVESTIDOR','RETIRADA_INVESTIDOR',
  'FREEBET_CREDITADA','FREEBET_CONSUMIDA','FREEBET_EXPIRADA','FREEBET_CONVERTIDA','FREEBET_ESTORNO',
  'RENOVACAO_PARCERIA','BONIFICACAO_ESTRATEGICA'
]));