ALTER TABLE public.cash_ledger DROP CONSTRAINT cash_ledger_tipo_transacao_check;

ALTER TABLE public.cash_ledger ADD CONSTRAINT cash_ledger_tipo_transacao_check CHECK (
  tipo_transacao = ANY (ARRAY[
    'DEPOSITO','SAQUE','TRANSFERENCIA','AJUSTE_MANUAL','AJUSTE_SALDO',
    'APOSTA_STAKE','APOSTA_GREEN','APOSTA_RED','APOSTA_MEIO_GREEN','APOSTA_MEIO_RED',
    'APOSTA_VOID','APOSTA_REEMBOLSO','APOSTA_REVERSAO',
    'FREEBET_CREDITADA','FREEBET_CONSUMIDA','FREEBET_EXPIRADA','FREEBET_ESTORNO','FREEBET_CONVERTIDA',
    'BONUS_CREDITADO','BONUS_ESTORNO',
    'CASHBACK_CREDITADO','CASHBACK_ESTORNO','CASHBACK_MANUAL',
    'GIRO_GRATIS','GIRO_GRATIS_ESTORNO',
    'COMISSAO','DESPESA','RECEITA','INVESTIMENTO','RESGATE',
    'APORTE_FINANCEIRO','RETIRADA_FINANCEIRA',
    'PERDA_CAMBIAL','GANHO_CAMBIAL','TAXA_REDE',
    'AJUSTE_RECONCILIACAO',
    'PAGAMENTO_TITULAR','ESTORNO_PAGAMENTO_TITULAR',
    'SWAP_OUT','SWAP_IN',
    'REVERSAO_AUDITORIA','ALOCACAO_FORNECEDOR','BONIFICACAO_ESTRATEGICA',
    'COMISSAO_INDICADOR','DEPOSITO_VIRTUAL','DESPESA_ADMINISTRATIVA',
    'ESTORNO','PAGTO_FORNECEDOR','PAGTO_OPERADOR','PAGTO_PARCEIRO',
    'PERDA_OPERACIONAL','PERDA_REVERSAO','RENOVACAO_PARCERIA','SAQUE_VIRTUAL'
  ])
);